#include "vulkan.hpp"

#include "scene/depth.cpp"
#include "scene/descriptor.cpp"
#include "scene/framebuffer.cpp"
#include "scene/output.cpp"
#include "scene/pipeline.cpp"
#include "scene/uniform.cpp"

#include "vector/descriptor.cpp"
#include "vector/edges.cpp"
#include "vector/output.cpp"
#include "vector/pipeline.cpp"

#include "buffer.cpp"
#include "cleanup.cpp"
#include "commands.cpp"
#include "contourImage.cpp"
#include "depth.cpp"
#include "descriptors.cpp"
#include "events.cpp"
#include "frame.cpp"
#include "helpers.cpp"
#include "instance.cpp"
#include "pipeline.cpp"
#include "rect.cpp"
#include "renderpass.cpp"
#include "scene.cpp"
#include "setup.cpp"
#include "submit.cpp"
#include "swapchain.cpp"
#include "sync.cpp"
#include "system.cpp"
#include "text.cpp"
#include "texture.cpp"
#include "vector.cpp"